using UnityEngine;

namespace BasicRPG.Items
{
    public enum ItemCategory { Metal, Consumable, Equipment, Misc }
    public enum EquipSlot { None, Weapon, Armor }

    /// <summary>
    /// ScriptableObject definition for an item. One asset per item type; pickups, inventory
    /// stacks, and equipment slots reference these. Created via Assets ▶ Create ▶ BasicRPG ▶ Item,
    /// or generated by the scene builder.
    /// </summary>
    [CreateAssetMenu(menuName = "BasicRPG/Item", fileName = "Item")]
    public class ItemSO : ScriptableObject
    {
        [Tooltip("Stable identifier (e.g. \"iron\"). Unique per item.")]
        public string id;
        public string displayName;

        public ItemCategory category;
        public Sprite icon;            // optional art; UI uses a category color when null
        public bool stackable = true;
        public int maxStack = 99;

        [Header("Consumable")]
        public float healthRestore;
        public float staminaRestore;

        [Header("Equipment")]
        public EquipSlot equipSlot = EquipSlot.None;
        [Tooltip("Attack for weapons, defense for armor — used when combat is added.")]
        public int power;

        // ── Runtime id→ItemSO registry (for save/load: items are assets, not scene objects,
        // so resolve saved ids back to their ItemSO at load time). Populated as assets load.
        private static readonly System.Collections.Generic.Dictionary<string, ItemSO> byId =
            new System.Collections.Generic.Dictionary<string, ItemSO>();

        void OnEnable()
        {
            if (string.IsNullOrEmpty(id)) return;
            byId[id] = this;
        }

        void OnDisable()
        {
            if (!string.IsNullOrEmpty(id)) byId.Remove(id);
        }

        /// <summary>Resolve a saved item id back to its ItemSO, or null if not loaded.</summary>
        public static ItemSO GetById(string id) =>
            string.IsNullOrEmpty(id) || !byId.TryGetValue(id, out ItemSO item) ? null : item;
    }
}